version: '3.8'
services:
  main:
    build: ./main/
    image: "main_image"
    container_name: "main_service"
    ports:
      - "8080:8080"
    depends_on:
      - stats
      - db-main
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_main:5432/explorewithme
      - STATS_URL=http://stats_service:9090

  db-main:
    image: postgres:13.7-alpine
    container_name: "db_main"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats:
    build: ./stats/
    image: "stats_image"
    container_name: "stats_service"
    ports:
      - "9090:9090"
    depends_on:
      - db-stats
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_stats:5432/explorewithme

  db-stats:
    image: postgres:13.7-alpine
    container_name: "db_stats"
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root